name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v -j 8
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
