name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v -j 8
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Codecov
      run: xcrun llvm-cov export -format="lcov" .build/debug/DeepSwiftPackageTests.xctest/Contents/MacOS/DeepSwiftPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
           bash <(curl https://codecov.io/bash)
